FROM openjdk:11
ADD ./target/config-server-pattern-0.0.1-SNAPSHOT.jar /usr/src/config-server-pattern-0.0.1-SNAPSHOT.jar
WORKDIR usr/src
ENTRYPOINT ["java","-jar","config-server-pattern-0.0.1-SNAPSHOT.jar"]
